version: "2.1"
services:
  db:
      image: "mysql:latest"
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD : kelompok48
        MYSQL_DATABASE: koba-test
      
  koba_api:
    image: "harutouko/koba-api:3.0"
    restart: always
    environment:
      SERVER_ADDRESS: "0.0.0.0:8149"
      DB_HOST: "db"
    ports:
      - "80:8149"